name: "chapados.org"
subtitle: "science, software and writing by Brian Chapados"
url: http://chapados.org

destination: ./_site
lsi:         false
port:        4000
highlighter: null
markdown:    rdiscount
permalink:   /:year/:month/:day/:title.html
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
